spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elite_homes_root?serverTimezone=UTC
    username: root
    password: 12345678

logging.config: classpath:logback-spring-local.xml

app.host: http://localhost:8070/