server:
  port: ${PORT:8045}

spring.profiles.active: ${SPRING_BOOT_PROFILE:local}

spring:
  hibernate:
    ddl-auto: validate
  mustache:
      check-template-location: false
  flyway.enabled: false
vaadin:
  launch-browser: true
  productionMode: false
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.wontlost,com.flowingcode.addons.carousel
  vaadin.allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.wontlost,com.flowingcode.addons.carousel

logging:
  level:
    org:
      atmosphere: warn

#
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: schema.sql
#spring.jpa.properties.hibernate.format_sql: true

